### ISSUE TITLE
Error in if (tipsonly) { : the condition has length > 1

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/phylodynamicsFundamentals#2]
Dear @LeoFeatherstone ,

Could you please help me out:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/65ec9407-934c-4172-aa4a-1c2cfcedd9cd">

Thanks.

Best,
Liam

**Comment by LeoFeatherstone** [comment]
Hi @liamxg,

I suspect something is wrong with your tree or install of NELSI, but I have no way of knowing without a line number or reference to the file where the code is from. Please provide a reproducible error and I may be able to help.

In any case, this is just code to produce an explanatory figure. You are welcome to reproduce the figure from the original paper by citing it instead of going to the trouble of rerunning this code.

All the best,
Leo

**Comment by liamxg** [comment]
Dear @LeoFeatherstone ,

Sorry for that.

This is come from the `demographicAssumptions.R` code of line 52, thank.


Best,
Liam
